services:
  bricks_finder:
    build:
      context: .
      dockerfile: gpu-Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./vector_indexes:/vector_indexes
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]