services:
  clip_finetuning:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: clip_finetuning
    volumes:
      - .:/clip_finetune
    stdin_open: true
    tty: true
    command:
      - /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]