services:
  clip_finetuning:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: clip_finetuning
    volumes:
      - ./src:/clip_finetune/src
      - ./finetuned_weights:/clip_finetune/weights
      - ../lego_bricks_dataset/processed_data:/lego_bricks_dataset/processed_data
    stdin_open: true
    tty: true
    command:
      - /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]