services:
  clip_finetuning:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: clip_finetuning
    env_file:
      - .env
    volumes:
      - ./finetune_results:/clip_finetune/finetune_results
    command: python3 src/entrypoint.py
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
